const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const http = require("node:http");
const { _electron } = require(process.env.PLAYWRIGHT_PATH || "playwright");
const root = path.resolve(__dirname, "..");
const directory = fs.mkdtempSync(path.join(os.tmpdir(), "btk-personal-smoke-"));
const output = path.join(root, "artifacts");
const fixtureKey = "fixture-native-encryption-only";
const requests = [];
const checks = [];
let instance;
const server = http.createServer(async (req, res) => {
  let body = "";
  for await (const chunk of req) body += chunk;
  const parsed = JSON.parse(body);
  requests.push({ body: parsed, url: req.url, hasExpectedKey: req.headers.authorization === `Bearer ${fixtureKey}` });
  if (parsed.messages.at(-1).content === "wait for cancel") return;
  res.writeHead(200, { "Content-Type": "application/json" });
  res.end(JSON.stringify({ choices: [{ message: { content: "Personal fixture response" }, finish_reason: "stop" }], usage: { prompt_tokens: 8, completion_tokens: 3, total_tokens: 11 } }));
});

async function launch() {
  const env = { ...process.env };
  delete env.ELECTRON_RUN_AS_NODE;
  instance = await _electron.launch({ executablePath: path.join(root, "node_modules/electron/dist/electron.exe"), args: [root, `--user-data-dir=${directory}`], env, timeout: 30000 });
  const page = await instance.firstWindow();
  await page.waitForFunction(() => Boolean(window.btk?.personal));
  return page;
}

(async () => {
  await new Promise(resolve => server.listen(0, "127.0.0.1", resolve));
  fs.mkdirSync(output, { recursive: true });
  let page = await launch();
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.getByRole("button", { name: "개인용 Personal" }).click();
  await page.getByRole("heading", { name: "모델 연결" }).waitFor();
  assert.equal(requests.length, 0);
  assert.equal((await page.evaluate(() => window.btk.personal.state())).mode, "personal");
  const centralBlocked = await page.evaluate(async () => { try { await window.btk.snapshot(); return false; } catch { return true; } });
  assert.equal(centralBlocked, true);
  checks.push("personal_boot_no_model_requests", "enterprise_ipc_rejected_in_personal");
  const isolation = await page.evaluate(() => ({ require: typeof require, process: typeof process }));
  assert.deepEqual(isolation, { require: "undefined", process: "undefined" });
  checks.push("renderer_node_isolation");
  await page.getByLabel("공급자", { exact: true }).selectOption("local");
  await page.getByLabel("API 주소", { exact: true }).fill(`http://127.0.0.1:${server.address().port}/v1`);
  await page.getByLabel("모델 ID", { exact: true }).fill("fixture-model");
  await page.getByLabel("API 키", { exact: true }).fill(fixtureKey);
  await page.getByRole("button", { name: "저장", exact: true }).click();
  await page.getByText("키 저장됨", { exact: true }).waitFor();
  assert.equal(await page.getByLabel("API 키", { exact: true }).inputValue(), "");
  const stored = fs.readFileSync(path.join(directory, "agent-ops-personal/personal.json"), "utf8");
  assert.equal(stored.includes(fixtureKey), false);
  const state = await page.evaluate(() => window.btk.personal.state());
  assert.equal(state.secureStorage, true);
  assert.equal(state.keyConfigured, true);
  assert.equal(JSON.stringify(state).includes(fixtureKey), false);
  assert.equal(requests.length, 0);
  checks.push("native_os_key_encryption", "no_plaintext_key_in_file_or_state", "save_does_not_send_request");
  await instance.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 0 }); });
  await page.getByRole("button", { name: "연결 시험", exact: true }).click();
  await page.getByRole("alert").waitFor();
  assert.equal(requests.length, 0);
  checks.push("cancelled_test_sends_nothing");
  await instance.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1 }); });
  await page.getByRole("button", { name: "연결 시험", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "연결 확인" }).waitFor();
  assert.equal(requests.length, 1);
  assert.equal(requests[0].hasExpectedKey, true);
  assert.equal(requests[0].body.max_tokens, 64);
  checks.push("native_ipc_model_probe");
  for (const width of [780, 1440]) {
    await instance.evaluate(({ BrowserWindow }, width) => BrowserWindow.getAllWindows()[0].setSize(width, 960), width);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.screenshot({ path: path.join(output, `personal-model-${width}.png`) });
  }
  checks.push("native_model_layout_780_1440");
  await page.getByRole("button", { name: "작업 공간", exact: true }).click();
  await page.getByLabel("개인 메시지", { exact: true }).fill("hello personal");
  await page.getByRole("button", { name: "개인 메시지 전송", exact: true }).click();
  await page.getByText("Personal fixture response", { exact: true }).waitFor();
  assert.equal(requests.length, 2);
  assert.deepEqual(requests[1].body.messages, [{ role: "user", content: "hello personal" }]);
  await page.getByRole("log", { name: "개인 대화" }).getByText("토큰 11", { exact: true }).waitFor();
  await page.screenshot({ path: path.join(output, "personal-chat-1440.png") });
  checks.push("native_chat_round_trip_and_measured_usage");
  await page.getByRole("button", { name: "새 대화", exact: true }).click();
  await page.getByLabel("개인 메시지", { exact: true }).fill("wait for cancel");
  await page.getByRole("button", { name: "개인 메시지 전송", exact: true }).click();
  await page.waitForTimeout(250);
  await page.getByRole("button", { name: "개인 답변 중단", exact: true }).click();
  await page.getByRole("alert").filter({ hasText: "취소" }).waitFor();
  assert.deepEqual(requests[2].body.messages, [{ role: "user", content: "wait for cancel" }]);
  checks.push("new_session_isolation", "native_cancel");
  await instance.close(); instance = null;
  const before = requests.length;
  page = await launch();
  await page.getByRole("heading", { name: "AEGIS Agent Ops", exact: true }).waitFor();
  assert.equal((await page.evaluate(() => window.btk.personal.state())).keyConfigured, true);
  assert.equal(requests.length, before);
  checks.push("restart_restores_mode_and_key_without_requests");
  await page.getByRole("button", { name: "모델 연결", exact: true }).click();
  await page.getByRole("button", { name: "저장된 키 삭제", exact: true }).click();
  await page.getByText("키 미등록", { exact: true }).waitFor();
  assert.equal(JSON.parse(fs.readFileSync(path.join(directory, "agent-ops-personal/personal.json"), "utf8")).encryptedKey, "");
  checks.push("native_key_removal");
  const slackToken = "xoxb-native-fixture-not-real";
  await page.evaluate(value => window.btk.personal.slack.save(value), slackToken);
  const slackState = await page.evaluate(() => window.btk.personal.slack.state());
  assert.equal(slackState.tokenConfigured, true);
  assert.equal(slackState.authenticated, false);
  assert.equal(slackState.agentCallable, false);
  assert.equal(JSON.stringify(slackState).includes(slackToken), false);
  assert.equal(fs.readFileSync(path.join(directory, "agent-ops-personal/personal.json"), "utf8").includes(slackToken), false);
  await page.evaluate(() => window.btk.personal.slack.enable(false));
  assert.equal((await page.evaluate(() => window.btk.personal.slack.state())).enabled, false);
  await page.evaluate(() => window.btk.personal.slack.remove());
  assert.equal((await page.evaluate(() => window.btk.personal.slack.state())).tokenConfigured, false);
  checks.push("native_slack_ipc_encrypted_storage_toggle_and_remove_no_network");
  await page.evaluate(() => window.btk.personal.mode("enterprise"));
  assert.equal((await page.evaluate(() => window.btk.personal.state())).mode, "enterprise");
  await page.evaluate(() => window.btk.personal.mode("personal"));
  checks.push("mode_switch_persistence");
  assert.deepEqual(errors, []);
  const result = { status: "passed", evidence_type: "native_electron_real_os_encryption_mock_loopback_model", checks, errors, actual_provider_verified: false, central_snapshot_blocked: true, checked_at: new Date().toISOString() };
  fs.writeFileSync(path.join(output, "personal-smoke.json"), JSON.stringify(result, null, 2));
  console.log(JSON.stringify(result));
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => {
  if (instance) await instance.close();
  server.closeAllConnections();
  await new Promise(resolve => server.close(resolve));
  fs.rmSync(directory, { recursive: true, force: true });
});
